// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class one_to_one_company_Location : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(one_to_one_company_Location));
        
        string IMigrationMetadata.Id
        {
            get { return "201703222238277_one_to_one_company_Location"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
